# Generated by Django 5.0.6 on 2024-06-02 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0002_remove_cartitem_price_cart_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
