# Generated by Django 5.0.6 on 2024-06-04 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0006_custommodelname'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomModelName',
        ),
    ]
